### ISSUE TITLE
Audio distortion and artifact issues with Rune playback

### ISSUE THREAD

**Issue by puff-dayo** [Losses/rune#151]
**Describe the bug**

I've noticed subtle audio distortions and artifacts when playing music through both my computer's built-in speakers and headphones. The audio sounds consistently hoarse with a persistent hum and intermittent popping sounds. So I switched to Windows's built-in media player for testing, then I noticed different sound quality.

Here is the frequency spectrum comparison between the original A(frequency=1760Hz, sample_rate = 44.1kHz) sine wave audio file and the recorded output file from Rune using an internal recording tool. I've attached both the test file and the recorded output for reference.

![](https://github.com/user-attachments/assets/619a1361-7512-46d8-a3ad-e8e95513352e)

(Upper: Internally recorded Rune audio playback. Lower: Program-generated sine wave audio)

**To Reproduce**
1. Simply play any sound.

**Desktop**
 - OS: Windows 11 21H2 22000.2538
 - Audio device: Headphones&Speakers (Realtek Audio) @ 2 channels, 24-bit, 48000Hz.
 - Version: Rune-v0.0.0-alpha.19-1d84138-windows

[sound_files.zip](https://github.com/user-attachments/files/17975759/sound_files.zip)

**Comment by puff-dayo** [comment]
The same issue can also be reproduced on one of my Linux PCs. 

Desktop

 - OS: Ubuntu 24.04 (Linux 6.8)
 - Audio device: Headphones&Speakers ALSA (Intel HDA) @ 2 channels, 32-bit, 48000Hz
 - Version: Rune-v0.0.0-alpha.20-linux-amd64

**Comment by XMLHexagram** [comment]
The same on macOS

The record of Rune output:
![CleanShot 2024-12-02 at 21 07 22@2x](https://github.com/user-attachments/assets/67209fe7-f668-4e49-9385-364bd81a4fc6)

The record of Apple Music output:
![CleanShot 2024-12-02 at 21 08 13@2x](https://github.com/user-attachments/assets/2eb11fad-dfc5-45ae-b581-0afcf4346428)

**Comment by Losses** [comment]
We appreciate your feedback regarding the audio output quality issues you encountered while using our software. We have conducted a thorough investigation and identified the core problem. It was determined that an incorrect API was used during audio visualization, which resulted in directly taking a sample from the buffer and causing sample loss. This led to imperfections in audio playback.

To address this, we have made modifications to the Rodio API, allowing us to extract data directly from the audio stream without compromising the audio decoding results. After implementing these changes, the issue of sample loss has been resolved, as confirmed by various spectrum analyses.

However, when playing a sine wave and extracting its spectrum, you may still notice artifacts. This is due to the underlying audio processing mechanisms of the entire tech stack. Specifically, there is a `0.05681818182%` discrepancy between the output frequency and the original audio frequency. This issue may stem from inherent digital system limitations or parameter rounding during processing. We believe this does not significantly impact auditory perception.

We are continuing to investigate this matter and hope that our current findings provide you with a better understanding of the situation.

**Comment by Losses** [comment]
In our continued investigation into the artifacts observed during sine wave audio playback, we have identified several complex contributing factors. To eliminate potential software-related influences, we controlled all external parameters: 
* We generated an audio file with a sample rate of 44100Hz, consisting of a 1000Hz mono sine wave. 
* Using OBS for recording, we set the recording parameters to 44100Hz as well to avoid resampling issues. 
* During the recording process, both the audio player's volume and the system volume were set to 100%. 

This resulted in a clean, smooth spectrum, indicating that there are no inherent development errors within Rune affecting audio quality.

![image](https://github.com/user-attachments/assets/a0fbadf8-b1c7-417e-832f-f5ccbc7616f8)

We observed that Rodio's resampling design has flaws, particularly when downsampling from 48000Hz to 44100Hz, resulting in suboptimal signal quality. 

![image](https://github.com/user-attachments/assets/845a571e-0344-4324-a51a-e11d790c7a91)

If we subtract Rodio's decoded output from the Ground Truth signal, the flaws in the resampling parameters become evident. 

![image](https://github.com/user-attachments/assets/581cbca8-2aab-461c-9d5e-810e29201fdc)

This issue is documented in the official repository's issue section. 

https://github.com/RustAudio/rodio/issues/647

We will continue to monitor upstream developments and apply updates promptly to ensure the best listening experience.
